name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build APK with Buildozer
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROIDSDK=$ANDROID_HOME
          export ANDROIDNDK=$ANDROID_HOME/ndk-bundle
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0:$PATH
          buildozer -v android release



      # Decode keystore from GitHub secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > mnkey.jks

      # Sign APK with jarsigner
      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore mnkey.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            bin/*.apk ${{ secrets.KEY_ALIAS }}

      # Verify signature
      - name: Verify APK Signature
        run: |
          jarsigner -verify -verbose -certs bin/*.apk

      # Upload signed Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: MNWebApp-release-apk
          path: bin/*.apk

      # Upload Debug APK too (optional)
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MNWebApp-debug-apk
          path: bin/*.apk
