name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04   # use fixed runner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          libltdl-dev \
          build-essential \
          git \
          zip unzip \
          openjdk-17-jdk \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          libncurses6 \
          libncurses-dev \
          libtinfo6 \
          libtinfo-dev \
          autopoint gettext \
          pkg-config \
          curl

    - name: Ensure libtool macros are available (fix LT_SYS_SYMBOL_USCORE)
      run: |
        mkdir -p $HOME/m4
        cp /usr/share/aclocal/libtool.m4 $HOME/m4/ || true
        cp /usr/share/aclocal/lt*.m4 $HOME/m4/ || true
        echo "ACLOCAL_PATH=$HOME/m4:/usr/share/aclocal" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Install Android SDK + NDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o sdk-tools.zip
        unzip -q sdk-tools.zip
        rm sdk-tools.zip
        mv cmdline-tools latest

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

        yes | sdkmanager --licenses
        yes | sdkmanager \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "ndk;25.2.9519653"

    - name: Fix sdkmanager path for Buildozer (symlink hack)
      run: |
        mkdir -p $HOME/android-sdk/tools/bin
        ln -s $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/android-sdk/tools/bin/sdkmanager

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Build release APK
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROIDNDK: $HOME/android-sdk/ndk/25.2.9519653
        ANDROIDAPI: "31"
        ANDROIDMINAPI: "21"
      run: |
        buildozer -v --log_level=2 android release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: bin/*.apk
